version: '3.9'

networks:
  finances.ntw:
    driver: bridge 

services:
  finances.api:
    image: finance
    container_name: finances.api
    restart: always
    depends_on:
      - finances.database
      - finances.cache
    environment:
      - ASPNETCORE_HTTP_PORTS=5000
      - Database=Host=finances.database;Port=5432;Database=finances;Username=postgres;Password=postgres;Include Error Detail=true
      - Cache=finances.cache:6379
    build: .
    ports:
      - "5000:5000"
    networks:
      - finances.ntw

  finances.database:
    image: postgres:latest
    container_name: finances.database
    restart: always
    environment:
      - POSTGRES_DB=finances
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/finance-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - finances.ntw
  
  finances.cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    networks:
      - finances.ntw
