version: '3.9'
services:
  webapi:
    image: finance
    container_name: finance-api
    environment:
      - ASPNETCORE_HTTP_PORTS=5000
    build: .
    ports:
      - "5000:5000"

  finance-database:
    image: postgres:latest
    container_name: finance.database
    environment:
      - POSTGRES_DB=finances
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/finance-db:/var/lib/postgressql/data
    ports:
      - 5432:5432
