version: '3.9'

networks:
  finances.ntw:
    driver: bridge 

services:
  finances.api:
    image: finance
    container_name: finances.api
    depends_on:
      - finances.database
    environment:
      - ASPNETCORE_HTTP_PORTS=5000
    build: .
    ports:
      - "5000:5000"
    networks:
      - finances.ntw

  finances.database:
    image: postgres:latest
    container_name: finances.database
    environment:
      - POSTGRES_DB=finances
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/finance-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - finances.ntw
